// react-redux-hello/src/components/Home/Home.js
import React, { Component } from 'react'
import { Link } from 'react-router-dom'
class Home extends Component {
  render() {
    const { topics } = this.props
    const topicList = topics.map(topic => (
      <li key={topic.id}>
        <Link to={`/topic/${topic.id}`}>{topic.title}</Link>
      </li>
    ))
    return (
      <div>
        <ul>{topicList}</ul>
      </div>
    )
  }
}

export default Home

// vue-post/src/components/Home.vue
<template>
  <div>
    <ul>
      <li v-for="post in posts" :key="post.id">
        <router-link to='/post'>{{post.title}}</router-link>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'home',
  data: () => ({
    posts: [
      {
        id: '1',
        title: 'vue 基础',
        content: '挺好的'
      },
      {
        id: '2',
        title: 'react 基础',
        content: '也不错'
      }
    ]
  })
}
</script>
